BKN-2973: refactor: Update presto-ui
juspay/presto-ui pull request #20
Opened 2023-03-10 14:21 UTC by kavyashree1998

Updated lastest presto-ui code

2023-03-11 01:47 UTC, murdore commented
@kavyashree1998
- Commit message needs to be updated with all the diff messages between version published vs current version.
- Are all the changes pulled? package.json version needs to be bumped up.

2023-03-11 03:52 UTC, JamesGeorg submitted a review, later dismissed

2023-03-13 15:28 UTC, murdore requested changes
@kavyashree1998 

    Commit message needs to be updated with all the diff messages between version published vs current version.
    Are all the changes pulled? package.json version needs to be bumped up.

2023-03-13 15:33 UTC, murdore approved these changes

2023-03-13 15:34 UTC, merged